export enum TagName {
    HTML = "HTML",
    HEAD = "HEAD",
    TITLE = "TITLE",
    BODY = "BODY",
    H1 = "H1",
    H2 = "H2",
    H3 = "H3",
    H4 = "H4",
    H5 = "H5",
    DIV = "DIV",
    P = "P",
    UL = "UL",
    OL = "OL",
    LI = "LI",
}